name: trackalz
description: A new Flutter project.

publish_to: 'none' 

environment:
  sdk: ">=2.11.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_map: ^0.12.0
  responsive_framework: ^0.1.2
  animations: ^2.0.1
  flutter_svg: ^0.19.3
  font_awesome_flutter: ^8.12.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/svgs/
    - assets/images/
    - assets/fonts/
