name: trackalz
description: A new Flutter project.

publish_to: 'none' 

environment:
  sdk: ">=2.11.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  responsive_framework: ^0.1.2
  animations: ^2.0.1
  flutter_svg: ^0.19.3
  font_awesome_flutter: ^8.12.0
  flutter_advanced_switch: ^1.0.0+1
  modal_progress_hud: ^0.1.3
  flutter_map: ^0.13.1
  latlong2: ^0.8.0
  geolocator: ^8.0.5
  flutter_sms_inbox: ^1.0.1
  permission_handler: ^8.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/svgs/
    - assets/images/
    - assets/fonts/
